# Site settings
title: "drekunia"
description: "Game developer and 3D artist creating games at the intersection of code and arts. Open to collaboration and connection."
url: "https://drekunia.github.io"
twitter_username: drekunia
image: /assets/img/og-image.png

# Build settings
markdown: kramdown
highlighter: rouge

# Author info
author:
  name: "drekunia"
  title: "Andre Kurniawan"
  bio: "I’m a game developer and 3D artist with programming experience and a passion for design and creative media. I enjoy combining code and arts to create games, and I’m always open to connecting with others who share the same passion."
  avatar: "/assets/img/avatar.webp"

# Social links
links:
  - name: showreel
    url: https://www.youtube.com/@drekunia
    bold: true
  - name: contact/inquiries
    url: mailto:drekunia@gmail.com
    same_tab: true
  - name: instagram
    url: https://instagram.com/drekunia
  - name: x/twitter
    url: https://x.com/drekunia
  # - name: linkedin
  #   url: https://www.linkedin.com/in/drekunia
  - name: itch.io
    url: https://drekunia.itch.io/
  - name: artstation
    url: https://www.artstation.com/drekunia
  - name: blog
    url: https://drekunia.github.io/blog
    same_tab: true
